# Minecart 2.1.0
# Plugin Feito por Angelo (@Th3Ang3lo) para Minecart
# Site https://minecart.com.br

Minecart:
  ShopKey: 'minecart_shop_key_api'
  ShopServer: 'minecart_server_name'

config:
  #Aviso de quando está aguardando retorno da informação
  #valores aceitos: popup, message, title
  #para desativar: none
  waiting_response_mode: 'popup'

  #Irá aparecer para todos os jogadores que você ativou uma key ou cash
  global_info: true